### ISSUE TITLE
Unable to query production server

### ISSUE THREAD

**Issue by feedXia** [apollographql/apollo-studio-community#184]
Hi,

I am following the Odyssey Lift-off V: Production & the Schema Registry tutorial and when I reach the section [Deploying our server ](https://www.apollographql.com/tutorials/lift-off-part5/deploying-apollo-server)and try to query the production server I get the following response in the Explorer:
```
{
  "name": "TypeError",
  "message": "Load failed"
}
```
And a pop up error `Unable to reach server`.

In the Heroic logs I can see the error
```
Error reporting server info to Apollo during schema reporting: Error: 406: Not Acceptable
```

When I run the diagnosis command `npx diagnose-endpoint@1.1.0 --endpoint=...` I get:
```
 Introspection query received a response of {"errors":[{"message":"GraphQL introspection is not allowed by Apollo Server, but the query contained __schema or __type. To enable introspection, pass introspection: true to ApolloServer in production","extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}]}
. Does introspection need to be turned on?
```

I have tried to troubleshoot by following the [Odyssey Full Stack Tutorial ](https://www.apollographql.com/tutorials/fullstack-quickstart/connecting-graphs-to-apollo-studio)and adding a `.env` file in my project root directory with my `APOLLO_KEY`, `APOLLO_GRAPH_REF` and `APOLLO_SCHEMA_REPORTING` and add `require('dotenv').config();` to the top of my `src/index.js` file even though this step is not included in this tutorial. 

Doing this gives me the following error in Heroku logs:
```
Error: Cannot find module 'dotenv'
2022-08-18T18:34:38.383720+00:00 app[web.1]: Require stack:
2022-08-18T18:34:38.383720+00:00 app[web.1]: - /app/src/index.js
2022-08-18T18:34:38.383732+00:00 app[web.1]:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
2022-08-18T18:34:38.383735+00:00 app[web.1]:     at Function.Module._load (node:internal/modules/cjs/loader:804:27)
2022-08-18T18:34:38.383735+00:00 app[web.1]:     at Module.require (node:internal/modules/cjs/loader:1028:19)
2022-08-18T18:34:38.383739+00:00 app[web.1]:     at require (node:internal/modules/cjs/helpers:102:18)
2022-08-18T18:34:38.383739+00:00 app[web.1]:     at Object.<anonymous> (/app/src/index.js:1:1)
2022-08-18T18:34:38.383740+00:00 app[web.1]:     at Module._compile (node:internal/modules/cjs/loader:1126:14)
2022-08-18T18:34:38.383740+00:00 app[web.1]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
2022-08-18T18:34:38.383740+00:00 app[web.1]:     at Module.load (node:internal/modules/cjs/loader:1004:32)
2022-08-18T18:34:38.383740+00:00 app[web.1]:     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
2022-08-18T18:34:38.383741+00:00 app[web.1]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
2022-08-18T18:34:38.383741+00:00 app[web.1]:   code: 'MODULE_NOT_FOUND',
2022-08-18T18:34:38.383741+00:00 app[web.1]:   requireStack: [ '/app/src/index.js' ]
2022-08-18T18:34:38.383741+00:00 app[web.1]: }
2022-08-18T18:34:38.612615+00:00 heroku[web.1]: State changed from starting to crashed
```

and running the diagnosis command gives me
```
 OPTIONS response is missing header 'access-control-allow-methods: POST'
⚠️  POST response missing 'access-control-allow-origin' header.
If using cookie-based authentication, the following headers are required from your endpoint: 
    access-control-allow-origin: https://studio.apollographql.com
    access-control-allow-credentials: true
Otherwise, a wildcard value would work:
    access-control-allow-origin: *
(📫 Interested in previewing a local tunnel to bypass CORS requirements? Please let us know at https://docs.google.com/forms/d/e/1FAIpQLScUCi3PdMerraiy6GpD-QiC_9KEKVHr4oDL5Vef5fIvzqqQWg/viewform )
```

Do you know what else I can try?

Thank you.

**Comment by abernix** [comment]
I'll still try to help you but I'm going to close this issue because this `apollo-studio-community` repository isn't the best repository for this issue to remain open (this is for conversations about Studio itself, but your dilemma seems to be around going through Odyssey).  We can still transfer it and re-open it elsewhere if that doesn't work out (which we probably should, if it turns out to be part of the tutorial!) and I can still engage while it's closed either way.

I think you're making progress by adding the `.env` file support via adding the `require('dotenv').config()`, but the error message you're seeing in the Heroku logs seems to indicate that the `dotenv` module isn't available in the environment.  It's crashing immediately when it starts up so Studio isn't able to do the CORS negotiation with the server because it's not even running!

The `dotenv` file doesn't seem to be installed and that might be because it's not declared in app's `package.json`'s `dependencies` section or because you didn't run `npm install` during the deployment process.

To start, maybe you run `npm install dot-env` and try deploying this application to Heroku again?

After you do that, you might try to see if it starts up successfully (without `State changed from starting to crashed` at the end!). If that's successful, you can run the `npx diagnose-endpoint ....` command again you used before to maybe get more information.

Hope this helps!

**Comment by feedXia** [comment]
Hi abernix,

Thank you so much for your response. I'm happy for this issue to be transferred to the appropriate place or stay here - whatever makes it easiest to resolve.

My endpoint: https://xia-server-catstronauts.herokuapp.com/

I noticed that `dotenv` was previously sitting in the ` "devDependencies"` section in my `package.json` so I have moved it to `dependencies` now. I have also ran `npm install dot-env`. 

After deploying to Heroku again the server now starts up, but in Apollo Studio Explorer I'm still getting the error message 
`Unable to reach server`.

The Heroku logs show:
```
Error reporting server info to Apollo during schema reporting: Error: 406: Not Acceptable
2022-08-19T11:33:20.809626+00:00 heroku[router]: at=info method=OPTIONS path="/" host=xia-server-catstronauts.herokuapp.com request_id=4fbebc8a-af22-4550-a649-2c09dc468f6b fwd="137.220.78.176" dyno=web.1 connect=0ms service=3ms status=204 bytes=278 protocol=https
```

When I run the `npx diagnose-endpoint ....` command at first I get:
```
Diagnosing https://xia-server-catstronauts.herokuapp.com/
⚠️  Introspection query received a response of {"errors":[{"message":"GraphQL introspection is not allowed by Apollo Server, but the query contained __schema or __type. To enable introspection, pass introspection: true to ApolloServer in production","extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}]}
. Does introspection need to be turned on?
```

So I've turned introspection on in my Apollo Server and now it says:
`Failed to diagnose any problems with the endpoint. Please email explorer-feedback@apollographql.com with the endpoint to help us investigate🙏
`

Here is my current `package.json`:

```
{
  "name": "catstronauts-server-complete",
  "version": "1.0.0",
  "description": "back-end demo app for Apollo's lift-off IV course",
  "main": "src/index.js",
  "scripts": {
    "start": "node src/index",
    "dev": "nodemon src/index"
  },
  "dependencies": {
    "apollo-datasource-rest": "^0.11.0",
    "apollo-server": "^3.0.0",
    "dot-env": "^0.0.1",
    "dotenv": "^16.0.1",
    "graphql": "^15.5.1"
  },
  "devDependencies": {
    "nodemon": "^2.0.4"
  },
  "author": "Raphael Terrier @R4ph-t",
  "license": "MIT",
  "private": true
}
```

**Comment by abernix** [comment]
> Failed to diagnose any problems with the endpoint.

This would give me the impression that querying from Studio should work now.  Are you still finding that to be the case?  If so, opening your Developer Tools (F11, I think?) and going to the Network panel should reveal the request that Studio is making to your Heroku URL and provide additional details.  You should also see something error-colored in the Console panel.

**Comment by feedXia** [comment]
Thank you for your reply.

Yes I am still unable to query from Apollo Studio.

In the Console Panel I see the following errors:
```
Access to fetch at 'https://xia-server-catstronauts.herokuapp.com/' from origin 'https://studio.apollographql.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'.

POST https://xia-server-catstronauts.herokuapp.com/ net::ERR_FAILED
```
In the network tab I also see a `CORS error`

I followed the [Configuring CORS in the Apollo Router](https://www.apollographql.com/docs/router/configuration/cors/) and [Configuring CORS](https://www.apollographql.com/docs/apollo-server/security/cors/#configuring-cors-options-for-apollo-server)  and added the following to the `ApolloServer` in `index.js` but receive the same error message.

Any suggestions will be much appreciated!

**Comment by feedXia** [comment]
I have just resolved it by adding
```
cors: {
      credentials: true,
      origin: ["https://xia-server-catstronauts.herokuapp.com/", "https://studio.apollographql.com"]
    },
```

and now I'm able to query my production server!

This part, including adding `require('dotenv').config();` was not in the Odyssey tutorials, so hopefully this issue can help others doing the tutorial!

**Comment by abernix** [comment]
thank you so much for reporting this! i'll get this feedback to the right team.
